# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_gibbs <- function(data, mu0, t20, nu0, s20, burnin = 1000L, iter = 1000L, chains = 1L) {
    .Call('RcppParallel_normal_gibbs', PACKAGE = 'RcppParallel', data, mu0, t20, nu0, s20, burnin, iter, chains)
}

